export const ActionTypes = {
	ADD_TODO: 'ADD_TODO',
	DELETE_FROM_TODO_LIST: 'DELETE_FROM_TODO_LIST',
	DELETE_FROM_COMPLITED_LIST: 'DELETE_FROM_COMPLITED_LIST',
	ADD_COMPLITED: 'ADD_COMPLITED',
	THEME: 'THEME',
};
